version: '2'
services:
  employees-app:
    build: app
    ports:
     - "8080:8080"
    depends_on:
     - employees-postgres
    links:
     - "employees-postgres:postgres"
    environment:
      POSTGRESQL_94_RHEL7_SERVICE_HOST: postgres
  employees-postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
     - "5432:5432"
